version: '3.8'

services:
  # ─── INFRASTRUCTURE ──────────────────────────────────────────────────────────
  
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # ─── MICROSERVICES ───────────────────────────────────────────────────────────

  identity-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: identity-service
    environment:
      DATABASE_URL: postgresql://user:pass@postgres:5432/shiftly_identity?schema=public
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - postgres
      - kafka

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: user-service
    environment:
      DATABASE_URL: postgresql://user:pass@postgres:5432/shiftly_users?schema=public
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - postgres
      - kafka

  jobs-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: jobs-service
    environment:
      DATABASE_URL: postgresql://user:pass@postgres:5432/shiftly_jobs?schema=public
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - postgres
      - kafka

  applications-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: applications-service
    environment:
      DATABASE_URL: postgresql://user:pass@postgres:5432/shiftly_applications?schema=public
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - postgres
      - kafka

  # ─── OBSERVABILITY ────────────────────────────────────────────────────────────
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
