apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- identity-service-deployment.yaml
- identity-service-service.yaml
- jobs-service-deployment.yaml
- jobs-service-service.yaml
- applications-service-deployment.yaml
- applications-service-service.yaml
- payments-service-deployment.yaml
- payments-service-service.yaml
- analytics-service-deployment.yaml
- analytics-service-service.yaml
- notifications-service-deployment.yaml
- notifications-service-service.yaml
- search-service-deployment.yaml
- search-service-service.yaml
- user-service-deployment.yaml
- user-service-service.yaml
- documents-service-deployment.yaml
- documents-service-service.yaml
- api-gateway-deployment.yaml
- api-gateway-service.yaml
