import { test, expect } from '@playwright/test';

test.describe('Application Cancellation Workflow', () => {
  test('Worker can apply and cancel an application', async ({ browser }) => {
    // Set up two separate contexts for Employer and Worker
    const employerContext = await browser.newContext();
    const workerContext = await browser.newContext();
    const employerPage = await employerContext.newPage();
    const workerPage = await workerContext.newPage();

    // --- 1. Employer Logs In ---
    await employerPage.goto('/login');
    await employerPage.click('text=Email');
    await employerPage.fill('input[type="email"]', 'employer@shiftly.local');
    await employerPage.fill('input[type="password"]', 'Password-123!');
    await employerPage.click('button[type="submit"]');
    await expect(employerPage).toHaveURL(/.*dashboard/, { timeout: 15000 });

    // --- 2. Worker Logs In ---
    await workerPage.goto('/login');
    await workerPage.click('text=Email');
    await workerPage.fill('input[type="email"]', 'worker@shiftly.local');
    await workerPage.fill('input[type="password"]', 'Password-123!');
    await workerPage.click('button[type="submit"]');
    await expect(workerPage).toHaveURL(/.*dashboard/, { timeout: 15000 });

    // --- 3. Employer Posts a Job ---
    await employerPage.click('text=Post a Job');
    await expect(employerPage).toHaveURL(/.*jobs\/post/);
    await employerPage.waitForTimeout(2000);

    const uniqueJobTitle = `Cancellation E2E Job ${Date.now()}`;
    await employerPage.getByLabel('Job Title').fill(uniqueJobTitle);
    await employerPage.getByLabel('Job Type').selectOption('PERMANENT');
    await employerPage.getByLabel('City').fill('Delhi');
    await employerPage.getByLabel('Min Salary').fill('500000');
    await employerPage.getByLabel('Max Salary').fill('1000000');
    await employerPage.getByLabel('Salary Period').selectOption('ANNUAL');
    await employerPage
      .getByLabel('Job Description')
      .fill('This is a test job description generated by playwright for cancellation flow.');
    await employerPage.getByRole('button', { name: 'Publish Job' }).click();

    await expect(employerPage).toHaveURL(/.*jobs\/[0-9a-f-]{36}/);
    const jobUrl = employerPage.url();
    const jobId = jobUrl.split('/').pop() as string;

    // --- 4. Worker Applies to the Job ---
    await workerPage.goto(`/jobs/${jobId}`);
    await expect(workerPage.locator('h1', { hasText: uniqueJobTitle })).toBeVisible();

    const applyButton = workerPage.getByRole('button', { name: 'Apply for this Job' });
    await expect(applyButton).toBeVisible();
    await applyButton.click();

    // Verify state changes
    await expect(
      workerPage.locator('text=Applied Successfully').or(workerPage.locator('text=Shortlisted')),
    ).toBeVisible();

    const cancelButton = workerPage.locator('button:has-text("Cancel Application")');
    await expect(cancelButton).toBeVisible();

    // --- 5. Cancel the application ---
    await cancelButton.click();

    const modalConfirmButton = workerPage.getByRole('button', { name: 'Withdraw' });
    
    await expect(modalConfirmButton).toBeVisible();
    await modalConfirmButton.click();

    // Verify the application is withdrawn
    await expect(workerPage.locator('text=Withdrawn')).toBeVisible();

    // The cancel button should be gone
    await expect(workerPage.locator('button:has-text("Cancel Application")')).toHaveCount(0);

    await employerContext.close();
    await workerContext.close();
  });
});
