import { test, expect } from '@playwright/test';
import { loginAsEmployer } from './test-utils';

test.describe('Employer Flow', () => {
  test('should login, post a job, and see it in manage jobs', async ({ page }) => {
    // 1. Login as Employer
    await loginAsEmployer(page);

    // 2. Navigate to Post Job
    await page.click('text=Post a Job');
    await expect(page).toHaveURL(/.*jobs\/post/);

    const uniqueJobTitle = `E2E Playwright Job ${Date.now()}`;

    // 3. Fill the form
    await page.getByLabel('Job Title').fill(uniqueJobTitle);
    await page.getByLabel('Job Type').selectOption('PERMANENT');
    await page.getByLabel('City').fill('Mumbai');
    await page.getByLabel('Min Salary').fill('500000');
    await page.getByLabel('Max Salary').fill('1000000');
    await page.getByLabel('Salary Period').selectOption('ANNUAL');
    await page.getByLabel('Job Description').fill('This is a test job description generated by playwright E2E testing framework. It needs to be at least 20 characters long.');

    // 4. Submit
    await page.getByRole('button', { name: 'Publish Job' }).click();

    // Wait for redirect to job details
    await expect(page).toHaveURL(/.*jobs\/[0-9a-f-]{36}/);
    await expect(page.locator('h1', { hasText: uniqueJobTitle })).toBeVisible();

    // 5. Navigate to Manage Jobs
    await page.click('text=Manage Jobs');
    await expect(page).toHaveURL(/.*jobs\/manage/);

    // Verify job appears in table
    await expect(page.locator('td', { hasText: uniqueJobTitle })).toBeVisible();
  });
});
