import { test, expect } from '@playwright/test';

test.describe('End-to-End Job Lifecycle', () => {
  test('employer creates job, worker applies, employer accepts', async ({ browser }) => {
    // Set up two separate contexts for Employer and Worker
    const employerContext = await browser.newContext();
    const workerContext = await browser.newContext();
    const employerPage = await employerContext.newPage();
    const workerPage = await workerContext.newPage();

    // --- 1. Employer Logs In ---
    await employerPage.goto('/login');
    await employerPage.click('text=Email');
    await employerPage.fill('input[type="email"]', 'employer@shiftly.com');
    await employerPage.fill('input[type="password"]', 'Password123!');
    await employerPage.click('button[type="submit"]');
    await expect(employerPage).toHaveURL(/.*dashboard/);

    // --- 2. Worker Logs In ---
    await workerPage.goto('/login');
    await workerPage.click('text=Email');
    await workerPage.fill('input[type="email"]', 'worker@shiftly.com');
    await workerPage.fill('input[type="password"]', 'Password123!');
    await workerPage.click('button[type="submit"]');
    await expect(workerPage).toHaveURL(/.*dashboard/);

    // --- 3. Employer Posts a Job ---
    await employerPage.click('text=Post a Job');
    await expect(employerPage).toHaveURL(/.*jobs\/post/);
    await employerPage.waitForTimeout(2000); // Wait for profile fetch and hydration

    const uniqueJobTitle = `Lifecycle E2E Job ${Date.now()}`;
    await employerPage.getByLabel('Job Title').fill(uniqueJobTitle);
    await employerPage.getByLabel('Job Type').selectOption('PERMANENT');
    await employerPage.getByLabel('City').fill('Mumbai');
    await employerPage.getByLabel('Min Salary').fill('600000');
    await employerPage.getByLabel('Max Salary').fill('1200000');
    await employerPage.getByLabel('Salary Period').selectOption('ANNUAL');
    await employerPage
      .getByLabel('Job Description')
      .fill(
        'This is a test job description generated by playwright E2E testing framework. It needs to be at least 20 characters long.',
      );
    await employerPage.getByRole('button', { name: 'Publish Job' }).click();

    // Wait for Job Details redirect and get the Job ID
    await expect(employerPage).toHaveURL(/.*jobs\/[0-9a-f-]{36}/);
    const jobUrl = employerPage.url();
    const jobId = jobUrl.split('/').pop() as string;

    // --- 4. Worker Applies to the Job ---
    // Worker goes directly to the job URL
    await workerPage.goto(`/jobs/${jobId}`);
    await expect(workerPage.locator('h1', { hasText: uniqueJobTitle })).toBeVisible();

    const applyButton = workerPage.getByRole('button', { name: 'Apply for this Job' });
    await expect(applyButton).toBeVisible();
    await applyButton.click();

    // Verify button state changes to "Applied Successfully"
    const appliedButton = workerPage.getByRole('button', { name: 'Applied Successfully' });
    await expect(appliedButton).toBeVisible();
    await expect(appliedButton).toBeDisabled();

    // Worker goes to My Applications
    await workerPage.click('text=My Applications');
    await expect(workerPage).toHaveURL(/.*applications/);
    await expect(workerPage.getByText(uniqueJobTitle)).toBeVisible();

    // --- 5. Employer Views Applications ---
    await employerPage.click('text=Manage Jobs');
    // Click on the applicants count or view button for this specific job
    // The Manage Jobs table should have a row for uniqueJobTitle
    const jobRow = employerPage.locator('tr', { hasText: uniqueJobTitle });
    // Assuming there's a view button or link to applications. We can just navigate to it:
    await employerPage.goto(`/jobs/${jobId}/applications`);

    // Verify Worker's application is present
    await expect(employerPage.getByText('John Doe')).toBeVisible(); // 'John Doe' is the test worker

    // Employer shortlists/accepts the application
    await employerPage.getByRole('button', { name: 'Shortlist' }).first().click();

    // --- 6. Worker Sees Updated Status ---
    await workerPage.reload();
    await expect(workerPage.locator('span', { hasText: 'SHORTLISTED' }).first()).toBeVisible();

    await employerContext.close();
    await workerContext.close();
  });
});
